name: Output information
on: workflow_dispatch

defaults:
  run:
    working-directory: ./Part1-Intro_to_actions/03+Finished+Project/03\ Finished\ Project

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"
